# This file was generated by GoReleaser. DO NOT EDIT.
class RailsInit < Formula
  desc "Initialize a Rails development environment on Mac."
  homepage ""
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/radar/rails-init/releases/download/v0.1.2/rails-init_0.1.2_darwin_amd64.tar.gz"
    sha256 "e448c23804e422874999fab0720abf8171b4b0fb8293b52eaee7e91f03b80a66"
  elsif OS.linux?
  end
  
  depends_on "asdf"

  def install
    bin.install "rails-init"
  end
end
