# This file was generated by GoReleaser. DO NOT EDIT.
class RailsInit < Formula
  desc "Initialize a Rails development environment on Mac."
  homepage ""
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/radar/rails-init/releases/download/v0.1.3/rails-init_0.1.3_darwin_amd64.tar.gz"
    sha256 "15b2626bc5ff953ba7e5d5529b7cd90de69587d32fd88deadb906e2729f5472a"
  elsif OS.linux?
  end
  
  depends_on "asdf"
  depends_on "gpg"

  def install
    bin.install "rails-init"
  end
end
